const PDFDocument = require("pdfkit");

const User = require("../models/User");
const Progress = require("../models/Progress");
const WorkoutPlan = require("../models/WorkoutPlan");
const DietPlan = require("../models/DietPlan");

const {
  ChartJSNodeCanvas,
} = require("chartjs-node-canvas");

const generateReport = async (
  req,
  res
) => {
  try {
    const user = await User.findById(
      req.user.id
    );

    const progress =
      await Progress.find({
        user: req.user.id,
      });

    const workouts =
      await WorkoutPlan.find({
        user: req.user.id,
      });

    const diets =
      await DietPlan.find({
        user: req.user.id,
      });

    // Generate Weight Chart
    const width = 600;
    const height = 300;

    const chartJSNodeCanvas =
      new ChartJSNodeCanvas({
        width,
        height,
      });

    const chartConfiguration = {
      type: "line",

      data: {
        labels: progress.map((item) =>
          new Date(
            item.createdAt
          ).toLocaleDateString()
        ),

        datasets: [
          {
            label: "Weight (kg)",

            data: progress.map(
              (item) => item.weight
            ),

            borderWidth: 3,

            tension: 0.4,
          },
        ],
      },

      options: {
        plugins: {
          legend: {
            display: true,
          },
        },
      },
    };

    const imageBuffer =
      await chartJSNodeCanvas.renderToBuffer(
        chartConfiguration
      );

    const doc = new PDFDocument({
      margin: 40,
    });

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=FitFlow_Report.pdf"
    );

    doc.pipe(res);

    // Title
    doc
      .fontSize(22)
      .text(
        "FitFlow Fitness Report",
        {
          align: "center",
        }
      );

    doc.moveDown(0.5);

    // User Info
    doc
      .fontSize(16)
      .text(
        "User Information",
        {
          underline: true,
        }
      );

    doc.moveDown(0.3);

    doc.fontSize(12);

    doc.text(
      `Name: ${user.name}`
    );

    doc.text(
      `Goal: ${user.goal}`
    );

    doc.text(
      `Weight: ${user.weight} kg`
    );

    doc.text(
      `Height: ${user.height} cm`
    );

    doc.moveDown(0.5);

    // Statistics
    doc
      .fontSize(16)
      .text(
        "Statistics",
        {
          underline: true,
        }
      );

    doc.moveDown(0.3);

    doc.fontSize(12);

    doc.text(
      `Workout Plans Generated: ${workouts.length}`
    );

    doc.text(
      `Diet Plans Generated: ${diets.length}`
    );

    doc.moveDown(0.5);

    // Chart Section
    doc
      .fontSize(16)
      .text(
        "Weight Progress Chart",
        {
          underline: true,
        }
      );

    doc.moveDown(0.3);

    doc.image(imageBuffer, {
      fit: [350, 180],
      align: "center",
    });

    doc.moveDown(0.5);

    // Summary
    const weights = progress.map(
      (p) => p.weight
    );

    if (weights.length > 0) {
      const startWeight =
        weights[0];

      const currentWeight =
        weights[
          weights.length - 1
        ];

      const difference =
        (
          startWeight -
          currentWeight
        ).toFixed(1);

      doc
        .fontSize(16)
        .text(
          "Progress Summary",
          {
            underline: true,
          }
        );

      doc.moveDown(0.3);

      doc.fontSize(12);

      doc.text(
        `Starting Weight: ${startWeight} kg`
      );

      doc.text(
        `Current Weight: ${currentWeight} kg`
      );

      doc.text(
        `Weight Change: ${difference} kg`
      );
    }

    doc.moveDown(1);

    doc
      .fontSize(10)
      .text(
        "Generated by FitFlow AI",
        {
          align: "center",
        }
      );

    doc.end();
  } catch (error) {
    res.status(500).json({
      message: error.message,
    });
  }
};

module.exports = {
  generateReport,
};